# Generated by Django 5.0.4 on 2026-01-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0002_material_product_alter_material_id_alter_product_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="product",
        ),
    ]
