# Generated by Django 5.0.4 on 2026-01-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_material_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
