# Generated by Django 5.0.4 on 2026-01-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warehouse",
            old_name="material_id",
            new_name="material",
        ),
    ]
